//go:build integration

package sourcecompat

var exactV22HistoryRetentionCatalog = map[string][]string{
	"retention_holds/columns": {
		"id|text|true|",
		"workspace_id|text|true|",
		"resource_kind|text|true|",
		"resource_id|text|true|",
		"reason|text|true|",
		"revision|bigint|true|1",
		"created_by|text|true|",
		"created_at|timestamp with time zone|true|",
		"released_by|text|false|",
		"released_at|timestamp with time zone|false|",
		"release_rationale|text|false|",
	},
	"retention_holds/constraints": {
		"app_retention_holds_check|CHECK ((released_by IS NULL) = (released_at IS NULL))",
		"app_retention_holds_check1|CHECK ((released_at IS NULL) = (release_rationale IS NULL))",
		"app_retention_holds_id_check|CHECK (id ~ '^[0-9a-f]{32}$'::text)",
		"app_retention_holds_pkey|PRIMARY KEY (id)",
		"app_retention_holds_reason_check|CHECK (octet_length(reason) >= 1 AND octet_length(reason) <= 8192)",
		"app_retention_holds_release_rationale_check|CHECK (release_rationale IS NULL OR octet_length(release_rationale) >= 1 AND octet_length(release_rationale) <= 8192)",
		"app_retention_holds_resource_id_check|CHECK (resource_id ~ '^[0-9a-f]{32}$'::text)",
		"app_retention_holds_resource_kind_check|" + V22RetentionHoldResourceKindCheck,
		"app_retention_holds_revision_check|CHECK (revision > 0)",
		"app_retention_holds_workspace_id_created_by_fkey|FOREIGN KEY (workspace_id, created_by) REFERENCES app_memberships(workspace_id, user_id)",
		"app_retention_holds_workspace_id_fkey|FOREIGN KEY (workspace_id) REFERENCES app_workspaces(id)",
		"app_retention_holds_workspace_id_key|UNIQUE (workspace_id, id)",
		"app_retention_holds_workspace_id_released_by_fkey|FOREIGN KEY (workspace_id, released_by) REFERENCES app_memberships(workspace_id, user_id)",
	},
	"retention_holds/indexes": {
		"app_retention_holds_active_resource|CREATE UNIQUE INDEX app_retention_holds_active_resource ON app_retention_holds USING btree (workspace_id, resource_kind, resource_id) WHERE (released_at IS NULL)",
		"app_retention_holds_pkey|CREATE UNIQUE INDEX app_retention_holds_pkey ON app_retention_holds USING btree (id)",
		"app_retention_holds_workspace_created|CREATE INDEX app_retention_holds_workspace_created ON app_retention_holds USING btree (workspace_id, created_at, id)",
		"app_retention_holds_workspace_id_key|CREATE UNIQUE INDEX app_retention_holds_workspace_id_key ON app_retention_holds USING btree (workspace_id, id)",
	},
	"retention_preview_items/columns": {
		"preview_id|text|true|",
		"workspace_id|text|true|",
		"ordinal|integer|true|",
		"class|text|true|",
		"resource_kind|text|true|",
		"resource_id|text|true|",
		"action|text|true|",
		"observed_at|timestamp with time zone|true|",
		"size_bytes|bigint|true|",
		"protected_reasons|jsonb|true|",
		"object_key|text|false|",
		"object_digest|text|false|",
		"object_revision|bigint|false|",
	},
	"retention_preview_items/constraints": {
		"app_retention_preview_items_action_check|CHECK (action = ANY (ARRAY['archive-history'::text, 'expire-archive'::text, 'expire-raw-report'::text, 'archive-audit'::text, 'delete-orphan'::text]))",
		"app_retention_preview_items_class_check|CHECK (class = ANY (ARRAY['hot-history'::text, 'archived-evidence'::text, 'raw-report'::text, 'audit'::text, 'orphan-archive'::text]))",
		"app_retention_preview_items_object_check|CHECK (resource_kind = 'archive-object'::text AND object_key IS NOT NULL AND object_digest ~ '^sha256:[0-9a-f]{64}$'::text AND object_revision > 0 OR resource_kind <> 'archive-object'::text AND object_key IS NULL AND object_digest IS NULL AND object_revision IS NULL)",
		"app_retention_preview_items_ordinal_check|CHECK (ordinal >= 0 AND ordinal <= 199)",
		"app_retention_preview_items_pkey|PRIMARY KEY (workspace_id, preview_id, ordinal)",
		"app_retention_preview_items_protected_reasons_check|CHECK (jsonb_typeof(protected_reasons) = 'array'::text)",
		"app_retention_preview_items_resource_id_check|CHECK (resource_id ~ '^[0-9a-f]{32}$'::text)",
		"app_retention_preview_items_resource_key|UNIQUE (workspace_id, preview_id, class, resource_kind, resource_id)",
		"app_retention_preview_items_resource_kind_check|" + V22RetentionPreviewResourceKindCheck,
		"app_retention_preview_items_size_bytes_check|CHECK (size_bytes >= 0)",
		"app_retention_preview_items_workspace_id_preview_id_fkey|FOREIGN KEY (workspace_id, preview_id) REFERENCES app_retention_previews(workspace_id, id) ON DELETE CASCADE",
	},
	"retention_preview_items/indexes": {
		"app_retention_preview_items_pkey|CREATE UNIQUE INDEX app_retention_preview_items_pkey ON app_retention_preview_items USING btree (workspace_id, preview_id, ordinal)",
		"app_retention_preview_items_preview|CREATE INDEX app_retention_preview_items_preview ON app_retention_preview_items USING btree (workspace_id, preview_id, ordinal)",
		"app_retention_preview_items_resource_key|CREATE UNIQUE INDEX app_retention_preview_items_resource_key ON app_retention_preview_items USING btree (workspace_id, preview_id, class, resource_kind, resource_id)",
	},
	"finding_decision_events/columns": {
		"id|text|true|",
		"workspace_id|text|true|",
		"finding_id|text|true|",
		"decision_revision|bigint|true|",
		"actor_id|text|true|",
		"action|text|true|",
		"rationale|text|true|",
		"changed_fields|jsonb|true|",
		"before_state|jsonb|true|",
		"after_state|jsonb|true|",
		"created_at|timestamp with time zone|true|",
	},
	"finding_decision_events/constraints": {
		"app_finding_decision_events_action_check|CHECK (action = ANY (ARRAY['update'::text, 'bulk-update'::text]))",
		"app_finding_decision_events_actor_id_fkey|FOREIGN KEY (actor_id) REFERENCES app_users(id)",
		"app_finding_decision_events_after_state_check|CHECK (jsonb_typeof(after_state) = 'object'::text)",
		"app_finding_decision_events_before_state_check|CHECK (jsonb_typeof(before_state) = 'object'::text)",
		"app_finding_decision_events_changed_fields_check|CHECK (jsonb_typeof(changed_fields) = 'array'::text)",
		"app_finding_decision_events_decision_revision_check|CHECK (decision_revision > 1)",
		"app_finding_decision_events_finding_revision_key|UNIQUE (workspace_id, finding_id, decision_revision)",
		"app_finding_decision_events_id_check|CHECK (id ~ '^[0-9a-f]{32}$'::text)",
		"app_finding_decision_events_pkey|PRIMARY KEY (id)",
		"app_finding_decision_events_rationale_check|CHECK (octet_length(rationale) <= 8192)",
		"app_finding_decision_events_workspace_id_finding_id_fkey|FOREIGN KEY (workspace_id, finding_id) REFERENCES app_findings(workspace_id, id) ON DELETE CASCADE",
		"app_finding_decision_events_workspace_id_key|UNIQUE (workspace_id, id)",
	},
	"finding_decision_events/indexes": {
		"app_finding_decision_events_finding_idx|CREATE INDEX app_finding_decision_events_finding_idx ON app_finding_decision_events USING btree (workspace_id, finding_id, decision_revision)",
		"app_finding_decision_events_finding_revision_key|CREATE UNIQUE INDEX app_finding_decision_events_finding_revision_key ON app_finding_decision_events USING btree (workspace_id, finding_id, decision_revision)",
		"app_finding_decision_events_pkey|CREATE UNIQUE INDEX app_finding_decision_events_pkey ON app_finding_decision_events USING btree (id)",
		"app_finding_decision_events_workspace_id_key|CREATE UNIQUE INDEX app_finding_decision_events_workspace_id_key ON app_finding_decision_events USING btree (workspace_id, id)",
	},
}
